CanInterface:
  ros__parameters:
    # Channels configuration
    channel0: "can0"
    bitrate0: 1000000
    # CAN messages to publish in ROS
    publishAMI505: true     # /ami_selected_mission
    publishAux166: true     # /brake_light
    publishAux336: true     # /ebs_tank_pressure
    publishAux357: true     # /rpm_rear
    publishAux384: true     # /tsal_safe_state
    publishAux412: true     # /cooling_info
    publishDash101: true    # /apps
    publishDash107: true    # /rpm_front
    publishDash198: true    # /brake
    publishDash204: true    # /dash_leds
    publishDash279: true    # /dash_buttons
    publishEBS550: true     # /ebs_supervisor_info
    publishSWA510: true     # /steering_actual

    # CAN messages to transmite
    transmiteAPU660: true   #can_as_state_mission
    transmiteSWA539: true   #can_steering_target
