/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.2.0 Sun Apr  4 21:52:20 2021.
 */

#ifndef CAN_AS_APU_RES_DLOGGER_H
#define CAN_AS_APU_RES_DLOGGER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define CAN_AS_APU_RES_DLOGGER_RES_STATUS_FRAME_ID (0x191u)

/* Frame lengths in bytes. */
#define CAN_AS_APU_RES_DLOGGER_RES_STATUS_LENGTH (8u)

/* Extended or standard frame types. */
#define CAN_AS_APU_RES_DLOGGER_RES_STATUS_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define CAN_AS_APU_RES_DLOGGER_RES_STATUS_STOP_ON_CHOICE (0u)
#define CAN_AS_APU_RES_DLOGGER_RES_STATUS_STOP_OFF_CHOICE (1u)

#define CAN_AS_APU_RES_DLOGGER_RES_STATUS_TOGGLE_OFF_CHOICE (0u)
#define CAN_AS_APU_RES_DLOGGER_RES_STATUS_TOGGLE_ON_CHOICE (1u)

#define CAN_AS_APU_RES_DLOGGER_RES_STATUS_BUTTON_OFF_CHOICE (0u)
#define CAN_AS_APU_RES_DLOGGER_RES_STATUS_BUTTON_ON_CHOICE (1u)

/**
 * Signals in message RES_STATUS.
 *
 * All signal values are as on the CAN bus.
 */
struct can_as_apu_res_dlogger_res_status_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t toggle;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t button;

    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t signal_strength;
};

/**
 * Pack message RES_STATUS.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_as_apu_res_dlogger_res_status_pack(
    uint8_t *dst_p,
    const struct can_as_apu_res_dlogger_res_status_t *src_p,
    size_t size);

/**
 * Unpack message RES_STATUS.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_as_apu_res_dlogger_res_status_unpack(
    struct can_as_apu_res_dlogger_res_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_as_apu_res_dlogger_res_status_stop_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_as_apu_res_dlogger_res_status_stop_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_as_apu_res_dlogger_res_status_stop_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_as_apu_res_dlogger_res_status_toggle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_as_apu_res_dlogger_res_status_toggle_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_as_apu_res_dlogger_res_status_toggle_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_as_apu_res_dlogger_res_status_button_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_as_apu_res_dlogger_res_status_button_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_as_apu_res_dlogger_res_status_button_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_as_apu_res_dlogger_res_status_signal_strength_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_as_apu_res_dlogger_res_status_signal_strength_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_as_apu_res_dlogger_res_status_signal_strength_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
