/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.1.0 Tue Feb  2 04:49:20 2021.
 */

#include <string.h>

#include "can_as_dash_aux.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int can_as_dash_aux_dash_101_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_dash_101_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_right_shift_u16(src_p->apps1_raw, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->apps1_raw, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->apps2_raw, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->apps2_raw, 0u, 0xffu);

    return (4);
}

int can_as_dash_aux_dash_101_unpack(
    struct can_as_dash_aux_dash_101_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->apps1_raw = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->apps1_raw |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->apps2_raw = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->apps2_raw |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);

    return (0);
}

uint16_t can_as_dash_aux_dash_101_apps1_raw_encode(double value)
{
    return (uint16_t)(value);
}

double can_as_dash_aux_dash_101_apps1_raw_decode(uint16_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_101_apps1_raw_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t can_as_dash_aux_dash_101_apps2_raw_encode(double value)
{
    return (uint16_t)(value);
}

double can_as_dash_aux_dash_101_apps2_raw_decode(uint16_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_101_apps2_raw_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_dash_198_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_dash_198_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->brake_raw, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->brake_raw, 0u, 0xffu);

    return (2);
}

int can_as_dash_aux_dash_198_unpack(
    struct can_as_dash_aux_dash_198_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->brake_raw = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->brake_raw |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

uint16_t can_as_dash_aux_dash_198_brake_raw_encode(double value)
{
    return (uint16_t)(value);
}

double can_as_dash_aux_dash_198_brake_raw_decode(uint16_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_198_brake_raw_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_dash_279_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_dash_279_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->enable_toggle, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->second_toggle, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->third_toggle_notused, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->start, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->ad_act, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->green_tsal, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->sc_state, 0u, 0xffu);

    return (7);
}

int can_as_dash_aux_dash_279_unpack(
    struct can_as_dash_aux_dash_279_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->enable_toggle = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->second_toggle = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->third_toggle_notused = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->start = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->ad_act = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->green_tsal = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->sc_state = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

uint8_t can_as_dash_aux_dash_279_enable_toggle_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_279_enable_toggle_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_279_enable_toggle_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_dash_279_second_toggle_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_279_second_toggle_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_279_second_toggle_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_dash_279_third_toggle_notused_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_279_third_toggle_notused_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_279_third_toggle_notused_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_dash_279_start_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_279_start_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_279_start_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_dash_279_ad_act_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_279_ad_act_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_279_ad_act_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_dash_279_green_tsal_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_279_green_tsal_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_279_green_tsal_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_dash_279_sc_state_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_279_sc_state_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_279_sc_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_dash_107_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_dash_107_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_right_shift_u32(src_p->hall_fl, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->hall_fl, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->hall_fl, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->hall_fl, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->hall_fr, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->hall_fr, 0u, 0xffu);

    return (6);
}

int can_as_dash_aux_dash_107_unpack(
    struct can_as_dash_aux_dash_107_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->hall_fl = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    dst_p->hall_fl |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    dst_p->hall_fl |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->hall_fl |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->hall_fr = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->hall_fr |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

uint32_t can_as_dash_aux_dash_107_hall_fl_encode(double value)
{
    return (uint32_t)(value);
}

double can_as_dash_aux_dash_107_hall_fl_decode(uint32_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_107_hall_fl_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint16_t can_as_dash_aux_dash_107_hall_fr_encode(double value)
{
    return (uint16_t)(value);
}

double can_as_dash_aux_dash_107_hall_fr_decode(uint16_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_107_hall_fr_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_aux_357_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_aux_357_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u32(src_p->hall_rl, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->hall_rl, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->hall_rl, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->hall_rl, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->hall_rr, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->hall_rr, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->hall_rr, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u32(src_p->hall_rr, 0u, 0xffu);

    return (8);
}

int can_as_dash_aux_aux_357_unpack(
    struct can_as_dash_aux_aux_357_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->hall_rl = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    dst_p->hall_rl |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    dst_p->hall_rl |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->hall_rl |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->hall_rr = unpack_left_shift_u32(src_p[4], 24u, 0xffu);
    dst_p->hall_rr |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    dst_p->hall_rr |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    dst_p->hall_rr |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);

    return (0);
}

uint32_t can_as_dash_aux_aux_357_hall_rl_encode(double value)
{
    return (uint32_t)(value);
}

double can_as_dash_aux_aux_357_hall_rl_decode(uint32_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_357_hall_rl_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t can_as_dash_aux_aux_357_hall_rr_encode(double value)
{
    return (uint32_t)(value);
}

double can_as_dash_aux_aux_357_hall_rr_decode(uint32_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_357_hall_rr_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_aux_384_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_aux_384_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->safe_state, 0u, 0xffu);

    return (7);
}

int can_as_dash_aux_aux_384_unpack(
    struct can_as_dash_aux_aux_384_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->safe_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

uint8_t can_as_dash_aux_aux_384_safe_state_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_aux_384_safe_state_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_384_safe_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_aux_412_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_aux_412_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->left_pump_signal, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->right_pump_signal, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->accu_fans_pwm, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->left_fans_pwm, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->right_fans_pwm, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->accu_fans, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->left_fans, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->right_fans, 0u, 0xffu);

    return (8);
}

int can_as_dash_aux_aux_412_unpack(
    struct can_as_dash_aux_aux_412_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->left_pump_signal = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->right_pump_signal = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->accu_fans_pwm = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->left_fans_pwm = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->right_fans_pwm = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->accu_fans = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->left_fans = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->right_fans = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t can_as_dash_aux_aux_412_left_pump_signal_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_aux_412_left_pump_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_412_left_pump_signal_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_aux_412_right_pump_signal_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_aux_412_right_pump_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_412_right_pump_signal_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_aux_412_accu_fans_pwm_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_aux_412_accu_fans_pwm_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_412_accu_fans_pwm_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_aux_412_left_fans_pwm_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_aux_412_left_fans_pwm_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_412_left_fans_pwm_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_aux_412_right_fans_pwm_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_aux_412_right_fans_pwm_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_412_right_fans_pwm_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_aux_412_accu_fans_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_aux_412_accu_fans_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_412_accu_fans_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_aux_412_left_fans_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_aux_412_left_fans_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_412_left_fans_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_aux_412_right_fans_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_aux_412_right_fans_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_412_right_fans_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_aux_166_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_aux_166_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->brakelight, 0u, 0xffu);

    return (1);
}

int can_as_dash_aux_aux_166_unpack(
    struct can_as_dash_aux_aux_166_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->brakelight = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

uint8_t can_as_dash_aux_aux_166_brakelight_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_aux_166_brakelight_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_166_brakelight_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_dash_204_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_dash_204_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->fan_pwm, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->buzzer, 4u, 0xf0u);
    dst_p[1] |= pack_left_shift_u8(src_p->safe_state_1, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->enable_out, 4u, 0xf0u);
    dst_p[2] |= pack_left_shift_u8(src_p->sensor_error, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->sc_software, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->pl_active, 0u, 0xffu);

    return (5);
}

int can_as_dash_aux_dash_204_unpack(
    struct can_as_dash_aux_dash_204_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->fan_pwm = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->buzzer = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);
    dst_p->safe_state_1 = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->enable_out = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    dst_p->sensor_error = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->sc_software = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->pl_active = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

uint8_t can_as_dash_aux_dash_204_fan_pwm_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_204_fan_pwm_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_204_fan_pwm_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_dash_204_buzzer_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_204_buzzer_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_204_buzzer_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t can_as_dash_aux_dash_204_safe_state_1_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_204_safe_state_1_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_204_safe_state_1_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t can_as_dash_aux_dash_204_enable_out_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_204_enable_out_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_204_enable_out_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t can_as_dash_aux_dash_204_sensor_error_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_204_sensor_error_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_204_sensor_error_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t can_as_dash_aux_dash_204_sc_software_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_204_sc_software_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_204_sc_software_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_dash_204_pl_active_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_dash_204_pl_active_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_dash_204_pl_active_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_aux_336_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_aux_336_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->ebs_pressure_raw, 0u, 0xffu);

    return (1);
}

int can_as_dash_aux_aux_336_unpack(
    struct can_as_dash_aux_aux_336_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->ebs_pressure_raw = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

uint8_t can_as_dash_aux_aux_336_ebs_pressure_raw_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_aux_336_ebs_pressure_raw_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_aux_336_ebs_pressure_raw_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_ami_505_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_ami_505_t *src_p,
    size_t size)
{
    uint8_t ami_mission;

    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    ami_mission = (uint8_t)src_p->ami_mission;
    dst_p[0] |= pack_left_shift_u8(ami_mission, 0u, 0xffu);

    return (1);
}

int can_as_dash_aux_ami_505_unpack(
    struct can_as_dash_aux_ami_505_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t ami_mission;

    if (size < 1u) {
        return (-EINVAL);
    }

    ami_mission = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ami_mission = (int8_t)ami_mission;

    return (0);
}

int8_t can_as_dash_aux_ami_505_ami_mission_encode(double value)
{
    return (int8_t)(value);
}

double can_as_dash_aux_ami_505_ami_mission_decode(int8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_ami_505_ami_mission_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_apu_660_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_apu_660_t *src_p,
    size_t size)
{
    uint8_t as_mission;
    uint8_t as_state;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    as_mission = (uint8_t)src_p->as_mission;
    dst_p[0] |= pack_left_shift_u8(as_mission, 0u, 0xffu);
    as_state = (uint8_t)src_p->as_state;
    dst_p[1] |= pack_left_shift_u8(as_state, 0u, 0xffu);

    return (2);
}

int can_as_dash_aux_apu_660_unpack(
    struct can_as_dash_aux_apu_660_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t as_mission;
    uint8_t as_state;

    if (size < 2u) {
        return (-EINVAL);
    }

    as_mission = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->as_mission = (int8_t)as_mission;
    as_state = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->as_state = (int8_t)as_state;

    return (0);
}

int8_t can_as_dash_aux_apu_660_as_mission_encode(double value)
{
    return (int8_t)(value);
}

double can_as_dash_aux_apu_660_as_mission_decode(int8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_apu_660_as_mission_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t can_as_dash_aux_apu_660_as_state_encode(double value)
{
    return (int8_t)(value);
}

double can_as_dash_aux_apu_660_as_state_decode(int8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_apu_660_as_state_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int can_as_dash_aux_swa_510_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_swa_510_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->steering_actual, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->steering_actual, 8u, 0xffu);

    return (2);
}

int can_as_dash_aux_swa_510_unpack(
    struct can_as_dash_aux_swa_510_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->steering_actual = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->steering_actual |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

uint16_t can_as_dash_aux_swa_510_steering_actual_encode(double value)
{
    return (uint16_t)(value);
}

double can_as_dash_aux_swa_510_steering_actual_decode(uint16_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_swa_510_steering_actual_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int can_as_dash_aux_swa_530_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_swa_530_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->steering_target, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->steering_target, 8u, 0xffu);

    return (2);
}

int can_as_dash_aux_swa_530_unpack(
    struct can_as_dash_aux_swa_530_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->steering_target = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->steering_target |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

uint16_t can_as_dash_aux_swa_530_steering_target_encode(double value)
{
    return (uint16_t)(value);
}

double can_as_dash_aux_swa_530_steering_target_decode(uint16_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_swa_530_steering_target_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int can_as_dash_aux_ebs_550_pack(
    uint8_t *dst_p,
    const struct can_as_dash_aux_ebs_550_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->asms_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->tsms_out, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->ebs_engaged, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->ebs_is_armed, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->ebs_led, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->k2_state, 0u, 0xffu);

    return (6);
}

int can_as_dash_aux_ebs_550_unpack(
    struct can_as_dash_aux_ebs_550_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->asms_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->tsms_out = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->ebs_engaged = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->ebs_is_armed = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->ebs_led = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->k2_state = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

uint8_t can_as_dash_aux_ebs_550_asms_state_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_ebs_550_asms_state_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_ebs_550_asms_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_ebs_550_tsms_out_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_ebs_550_tsms_out_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_ebs_550_tsms_out_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_ebs_550_ebs_engaged_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_ebs_550_ebs_engaged_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_ebs_550_ebs_engaged_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_ebs_550_ebs_is_armed_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_ebs_550_ebs_is_armed_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_ebs_550_ebs_is_armed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_ebs_550_ebs_led_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_ebs_550_ebs_led_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_ebs_550_ebs_led_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_as_dash_aux_ebs_550_k2_state_encode(double value)
{
    return (uint8_t)(value);
}

double can_as_dash_aux_ebs_550_k2_state_decode(uint8_t value)
{
    return ((double)value);
}

bool can_as_dash_aux_ebs_550_k2_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
