/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.2.0 Tue Apr  6 16:35:28 2021.
 */

#include <string.h>

#include "can_apu_res_dlogger.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int can_apu_res_dlogger_res_status_pack(
    uint8_t *dst_p,
    const struct can_apu_res_dlogger_res_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->stop, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->toggle, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->button, 2u, 0x04u);
    dst_p[6] |= pack_left_shift_u8(src_p->signal_strength, 0u, 0xffu);

    return (8);
}

int can_apu_res_dlogger_res_status_unpack(
    struct can_apu_res_dlogger_res_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->stop = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->toggle = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->button = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->signal_strength = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

uint8_t can_apu_res_dlogger_res_status_stop_encode(double value)
{
    return (uint8_t)(value);
}

double can_apu_res_dlogger_res_status_stop_decode(uint8_t value)
{
    return ((double)value);
}

bool can_apu_res_dlogger_res_status_stop_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_apu_res_dlogger_res_status_toggle_encode(double value)
{
    return (uint8_t)(value);
}

double can_apu_res_dlogger_res_status_toggle_decode(uint8_t value)
{
    return ((double)value);
}

bool can_apu_res_dlogger_res_status_toggle_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_apu_res_dlogger_res_status_button_encode(double value)
{
    return (uint8_t)(value);
}

double can_apu_res_dlogger_res_status_button_decode(uint8_t value)
{
    return ((double)value);
}

bool can_apu_res_dlogger_res_status_button_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_apu_res_dlogger_res_status_signal_strength_encode(double value)
{
    return (uint8_t)(value);
}

double can_apu_res_dlogger_res_status_signal_strength_decode(uint8_t value)
{
    return ((double)value);
}

bool can_apu_res_dlogger_res_status_signal_strength_is_in_range(uint8_t value)
{
    return (value <= 100u);
}
